apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /vol
        name: first-volume
  - name: jenkins-container
    image: jenkins/jenkins:latest
    volumeMounts:
      - mountPath: /vol
        name: first-volume
  volumes:
    - name: first-volume
      hostPath:
        path: /Users/bhborges/Desktop
        type: Directory
