apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-news-deployment
spec:
  selector:
    matchLabels:
      app: db-news-deployment
  template:
    metadata:
      labels:
        app: db-news-deployment
    spec:
      containers:
      - name: db-news
        image: aluracursos/mysql-db:1
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: db-configmap
