apiVersion: v1
kind: Pod
metadata:
  name: system-news
  labels:
    app: system-news
spec:
  containers:
  - name: system-news
    image: aluracursos/sistema-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: system-configmap
